### ISSUE TITLE
slideslive link

### ISSUE THREAD

**Issue by Karim-53** [PeymanMorteza/GEM#2]
Hi

I have the link for the intro prez on slideslive 
https://slideslive.com/38977694/provable-guarantees-for-understanding-outofdistribution-detection-intro 

but I lost the link for the full presentation
Could you please share it with us 

It would be helpful if you could add these to the Readme
Thanks

**Comment by PeymanMorteza** [comment]
Hi,

Thanks for your interest in our work. Here is a link to the full oral presentation: 
https://recorder-v3.slideslive.com/?share=60258&s=7cbd5173-f3aa-4f1e-9a08-bdfa63a8228e
